//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alchemy.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alchemy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на земля.
        /// </summary>
        internal static string id0 {
            get {
                return ResourceManager.GetString("id0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на огонь.
        /// </summary>
        internal static string id1 {
            get {
                return ResourceManager.GetString("id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на обсидиан.
        /// </summary>
        internal static string id10 {
            get {
                return ResourceManager.GetString("id10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minecraft.
        /// </summary>
        internal static string id11 {
            get {
                return ResourceManager.GetString("id11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на спирт.
        /// </summary>
        internal static string id12 {
            get {
                return ResourceManager.GetString("id12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на водка.
        /// </summary>
        internal static string id13 {
            get {
                return ResourceManager.GetString("id13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на болото.
        /// </summary>
        internal static string id14 {
            get {
                return ResourceManager.GetString("id14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бактерии.
        /// </summary>
        internal static string id15 {
            get {
                return ResourceManager.GetString("id15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на камень.
        /// </summary>
        internal static string id16 {
            get {
                return ResourceManager.GetString("id16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на яйцо.
        /// </summary>
        internal static string id17 {
            get {
                return ResourceManager.GetString("id17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на курица.
        /// </summary>
        internal static string id18 {
            get {
                return ResourceManager.GetString("id18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МакДональдс.
        /// </summary>
        internal static string id19 {
            get {
                return ResourceManager.GetString("id19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вода.
        /// </summary>
        internal static string id2 {
            get {
                return ResourceManager.GetString("id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля.
        /// </summary>
        internal static string id20 {
            get {
                return ResourceManager.GetString("id20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пыль.
        /// </summary>
        internal static string id21 {
            get {
                return ResourceManager.GetString("id21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на динозавр.
        /// </summary>
        internal static string id22 {
            get {
                return ResourceManager.GetString("id22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дракон.
        /// </summary>
        internal static string id23 {
            get {
                return ResourceManager.GetString("id23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на зверь.
        /// </summary>
        internal static string id24 {
            get {
                return ResourceManager.GetString("id24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на человек.
        /// </summary>
        internal static string id25 {
            get {
                return ResourceManager.GetString("id25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довакин.
        /// </summary>
        internal static string id26 {
            get {
                return ResourceManager.GetString("id26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на песок.
        /// </summary>
        internal static string id27 {
            get {
                return ResourceManager.GetString("id27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на голем.
        /// </summary>
        internal static string id28 {
            get {
                return ResourceManager.GetString("id28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на труд.
        /// </summary>
        internal static string id29 {
            get {
                return ResourceManager.GetString("id29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на воздух.
        /// </summary>
        internal static string id3 {
            get {
                return ResourceManager.GetString("id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на глина.
        /// </summary>
        internal static string id30 {
            get {
                return ResourceManager.GetString("id30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ожирение.
        /// </summary>
        internal static string id31 {
            get {
                return ResourceManager.GetString("id31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на алкоголик.
        /// </summary>
        internal static string id32 {
            get {
                return ResourceManager.GetString("id32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на секс.
        /// </summary>
        internal static string id33 {
            get {
                return ResourceManager.GetString("id33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на инструменты.
        /// </summary>
        internal static string id34 {
            get {
                return ResourceManager.GetString("id34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на алмазы.
        /// </summary>
        internal static string id35 {
            get {
                return ResourceManager.GetString("id35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на украшения.
        /// </summary>
        internal static string id36 {
            get {
                return ResourceManager.GetString("id36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на горы.
        /// </summary>
        internal static string id37 {
            get {
                return ResourceManager.GetString("id37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на страна.
        /// </summary>
        internal static string id38 {
            get {
                return ResourceManager.GetString("id38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Россия.
        /// </summary>
        internal static string id39 {
            get {
                return ResourceManager.GetString("id39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на лава.
        /// </summary>
        internal static string id4 {
            get {
                return ResourceManager.GetString("id4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Америка.
        /// </summary>
        internal static string id40 {
            get {
                return ResourceManager.GetString("id40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ядерная бомба.
        /// </summary>
        internal static string id41 {
            get {
                return ResourceManager.GetString("id41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дерево.
        /// </summary>
        internal static string id42 {
            get {
                return ResourceManager.GetString("id42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бумага.
        /// </summary>
        internal static string id43 {
            get {
                return ResourceManager.GetString("id43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на книги.
        /// </summary>
        internal static string id44 {
            get {
                return ResourceManager.GetString("id44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на книжный шкаф.
        /// </summary>
        internal static string id45 {
            get {
                return ResourceManager.GetString("id45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на метал.
        /// </summary>
        internal static string id46 {
            get {
                return ResourceManager.GetString("id46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 123.
        /// </summary>
        internal static string id47 {
            get {
                return ResourceManager.GetString("id47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на энергия.
        /// </summary>
        internal static string id5 {
            get {
                return ResourceManager.GetString("id5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на жизнь.
        /// </summary>
        internal static string id6 {
            get {
                return ResourceManager.GetString("id6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пар.
        /// </summary>
        internal static string id7 {
            get {
                return ResourceManager.GetString("id7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на трава.
        /// </summary>
        internal static string id8 {
            get {
                return ResourceManager.GetString("id8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1UP.
        /// </summary>
        internal static string id9 {
            get {
                return ResourceManager.GetString("id9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
